SET FOREIGN_KEY_CHECKS=0; SET NAMES utf8mb4;
CREATE TABLE roles(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,nombre VARCHAR(60) NOT NULL,descripcion VARCHAR(255),PRIMARY KEY(id),UNIQUE KEY uq_roles_nombre(nombre))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO roles(nombre,descripcion) VALUES('Administrador','Acceso total'),('Operador','Carga y consulta'),('Visor','Solo lectura');
CREATE TABLE usuarios(id INT UNSIGNED NOT NULL AUTO_INCREMENT,nombre VARCHAR(120) NOT NULL,email VARCHAR(180) NOT NULL,password_hash VARCHAR(255) NOT NULL,rol_id TINYINT UNSIGNED NOT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,avatar_url VARCHAR(500),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_usuarios_email(email),KEY idx_usuarios_rol(rol_id),CONSTRAINT fk_usuarios_rol FOREIGN KEY(rol_id) REFERENCES roles(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Subroles (Secuencia 7 - subroles.sql): control de acceso por modulo de
-- negocio (ARDUM/ARDUM HL/Empresas Chinas) solo para roles editor/visor;
-- admin/superadmin no usan subrol (acceso total siempre).
CREATE TABLE subroles(id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,clave VARCHAR(30) NOT NULL,nombre VARCHAR(60) NOT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_subrol_clave(clave))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE usuario_subroles(id INT UNSIGNED NOT NULL AUTO_INCREMENT,usuario_id INT UNSIGNED NOT NULL,subrol_id SMALLINT UNSIGNED NOT NULL,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_usuario_subrol(usuario_id,subrol_id),KEY idx_us_subrol(subrol_id),CONSTRAINT fk_us_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,CONSTRAINT fk_us_subrol FOREIGN KEY(subrol_id) REFERENCES subroles(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- ARDUM (Secuencia 2 - ardum.sql): empresas..valores_columnas_personalizadas
-- sincronizadas con la BD real. Todas incluyen columnas de auditoria
-- (creado_por, modificado_por, created_at, updated_at) por convencion.
CREATE TABLE empresas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,nombre VARCHAR(150) NOT NULL,tipo ENUM('nacional','china') NOT NULL DEFAULT 'nacional',slug VARCHAR(160) NOT NULL,activa TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_empresas_slug(slug),KEY idx_empresas_tipo(tipo))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE empresa_usuario(empresa_id INT UNSIGNED NOT NULL,usuario_id INT UNSIGNED NOT NULL,PRIMARY KEY(empresa_id,usuario_id),KEY idx_eu_usuario(usuario_id),CONSTRAINT fk_eu_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id) ON DELETE CASCADE,CONSTRAINT fk_eu_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE propietarios(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,nombre VARCHAR(180) NOT NULL,numero_lote VARCHAR(20),curp CHAR(18),email VARCHAR(180),telefono VARCHAR(20),activo TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_propietarios_empresa(empresa_id),KEY idx_propietarios_curp(curp),KEY idx_propietarios_numero_lote(numero_lote),KEY idx_propietarios_deleted(deleted_at),CONSTRAINT fk_prop_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE tipos_documento(id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,clave VARCHAR(60) NOT NULL,nombre VARCHAR(180) NOT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tipos_doc_clave(clave))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE documentos(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,propietario_id INT UNSIGNED,tipo_documento_id SMALLINT UNSIGNED NOT NULL,nombre_archivo VARCHAR(300) NOT NULL,ruta_storage VARCHAR(500) NOT NULL,mime_type VARCHAR(100) NOT NULL,tamano_bytes INT UNSIGNED NOT NULL,subido_por INT UNSIGNED NOT NULL,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_docs_empresa(empresa_id),KEY idx_docs_propietario(propietario_id),KEY idx_docs_tipo(tipo_documento_id),KEY idx_docs_deleted(deleted_at),CONSTRAINT fk_docs_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id),CONSTRAINT fk_docs_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE SET NULL,CONSTRAINT fk_docs_tipo FOREIGN KEY(tipo_documento_id) REFERENCES tipos_documento(id),CONSTRAINT fk_docs_subido FOREIGN KEY(subido_por) REFERENCES usuarios(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE columnas_personalizadas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,seccion VARCHAR(80) NOT NULL,nombre VARCHAR(120) NOT NULL,tipo ENUM('texto','numero','fecha','archivo','boolean') NOT NULL DEFAULT 'texto',orden SMALLINT UNSIGNED NOT NULL DEFAULT 0,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_col_empresa_seccion(empresa_id,seccion),KEY idx_colpers_deleted(deleted_at),CONSTRAINT fk_col_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- NOTA: Empresas Chinas (Secuencia 4) no tiene UI de columnas personalizadas,
-- por lo que valores_columnas_personalizadas no requiere empresa_china_id.
CREATE TABLE valores_columnas_personalizadas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,columna_id INT UNSIGNED NOT NULL,propietario_id INT UNSIGNED NOT NULL,valor_texto TEXT,valor_documento_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_vcp_columna_propietario(columna_id,propietario_id),KEY idx_vcp_columna(columna_id),KEY idx_vcp_propietario(propietario_id),CONSTRAINT fk_vcp_columna FOREIGN KEY(columna_id) REFERENCES columnas_personalizadas(id) ON DELETE CASCADE,CONSTRAINT fk_vcp_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_vcp_documento FOREIGN KEY(valor_documento_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE documentos_personales(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,contrato_ardum_id INT UNSIGNED,contrato_hegewisch_id INT UNSIGNED,csf_id INT UNSIGNED,acuse_cita_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_dp_propietario(propietario_id),KEY idx_docpers_deleted(deleted_at),CONSTRAINT fk_dp_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_dp_ardum FOREIGN KEY(contrato_ardum_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_dp_hegewisch FOREIGN KEY(contrato_hegewisch_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_dp_csf FOREIGN KEY(csf_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_dp_acuse FOREIGN KEY(acuse_cita_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE fiel_registros(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,clave_privada_id INT UNSIGNED,certificado_id INT UNSIGNED,contrasena VARCHAR(500),fecha_creacion DATE,fecha_vencimiento DATE,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_fiel_propietario(propietario_id),KEY idx_fiel_deleted(deleted_at),KEY idx_fiel_vencimiento(fecha_vencimiento),CONSTRAINT fk_fiel_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_fiel_clave FOREIGN KEY(clave_privada_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_fiel_cert FOREIGN KEY(certificado_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE declaraciones(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,tipo ENUM('mensual','mensual_cero') NOT NULL DEFAULT 'mensual',siguiente_pago_frecuencia ENUM('mensual','bimestral','anual') NOT NULL DEFAULT 'mensual',fecha_ultimo_pago DATE,fecha_declaracion DATE,comprobante_id INT UNSIGNED,periodo_mes TINYINT UNSIGNED NOT NULL,periodo_anio YEAR NOT NULL,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_decl_propietario(propietario_id),KEY idx_decl_periodo(periodo_anio,periodo_mes),KEY idx_decl_deleted(deleted_at),CONSTRAINT fk_decl_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_decl_comprobante FOREIGN KEY(comprobante_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE facturas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,fecha DATE NOT NULL,comprobante_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_fact_propietario(propietario_id),KEY idx_fact_fecha(fecha),KEY idx_fact_deleted(deleted_at),CONSTRAINT fk_fact_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_fact_comprobante FOREIGN KEY(comprobante_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Empresas Chinas (Secuencia 4 - empresas chinas.sql): auditoria completa +
-- deleted_at donde aplica papelera, mismas reglas que ARDUM (Secuencia 2).
CREATE TABLE etapa_requisitos(id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,etapa_num TINYINT UNSIGNED NOT NULL,codigo VARCHAR(10) NOT NULL,descripcion VARCHAR(500) NOT NULL,tipo_campo ENUM('archivo','texto','numero','boolean') NOT NULL DEFAULT 'archivo',creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_etapa_req_codigo(etapa_num,codigo),KEY idx_er_etapa(etapa_num))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE empresas_chinas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,codigo VARCHAR(20) NOT NULL,nombre VARCHAR(180) NOT NULL,representante_legal VARCHAR(180),correo_electronico VARCHAR(180),telefono VARCHAR(30),fecha_registro DATE,etapa_actual TINYINT UNSIGNED NOT NULL DEFAULT 1,estado ENUM('en_proceso','pendiente','finalizada','archivada') NOT NULL DEFAULT 'en_proceso',progreso_pct TINYINT UNSIGNED NOT NULL DEFAULT 0,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_ec_codigo(codigo),KEY idx_ec_estado(estado),KEY idx_ec_deleted(deleted_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE empresa_china_requisitos(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_china_id INT UNSIGNED NOT NULL,requisito_id SMALLINT UNSIGNED NOT NULL,documento_id INT UNSIGNED,valor_texto TEXT,completado TINYINT(1) NOT NULL DEFAULT 0,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_ecr(empresa_china_id,requisito_id),KEY idx_ecr_deleted(deleted_at),CONSTRAINT fk_ecr_empresa FOREIGN KEY(empresa_china_id) REFERENCES empresas_chinas(id) ON DELETE CASCADE,CONSTRAINT fk_ecr_requisito FOREIGN KEY(requisito_id) REFERENCES etapa_requisitos(id),CONSTRAINT fk_ecr_documento FOREIGN KEY(documento_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE empresa_china_etapa_checklist(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_china_id INT UNSIGNED NOT NULL,etapa_num TINYINT UNSIGNED NOT NULL,completada TINYINT(1) NOT NULL DEFAULT 0,completada_en DATETIME,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_ecec(empresa_china_id,etapa_num),CONSTRAINT fk_ecec_empresa FOREIGN KEY(empresa_china_id) REFERENCES empresas_chinas(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE configuracion_notificaciones(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,tipo VARCHAR(80) NOT NULL,dia_del_mes TINYINT UNSIGNED NOT NULL,activa TINYINT(1) NOT NULL DEFAULT 1,PRIMARY KEY(id),KEY idx_cn_empresa(empresa_id),CONSTRAINT fk_cn_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Configuracion alertas FIEL (Secuencia 8 - configuracion alertas fiel.sql):
-- singleton (id=1) con los dias de anticipacion del job de vencimientos de
-- FIEL, configurable por admin/superadmin desde el modulo Configuracion.
CREATE TABLE configuracion_alertas_fiel(id TINYINT UNSIGNED NOT NULL,dias_anticipacion TINYINT UNSIGNED NOT NULL DEFAULT 3,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Notificaciones (Secuencia 3 - notificaciones.sql): generica y reutilizable
-- via origen_tabla/origen_id; hoy alimentada por el job de vencimientos FIEL.
CREATE TABLE notificaciones(id INT UNSIGNED NOT NULL AUTO_INCREMENT,usuario_id INT UNSIGNED NOT NULL,tipo VARCHAR(60) NOT NULL,origen_tabla VARCHAR(60) NOT NULL,origen_id INT UNSIGNED NOT NULL,dias_restantes TINYINT NOT NULL,titulo VARCHAR(200) NOT NULL,cuerpo VARCHAR(500) NOT NULL,ruta VARCHAR(300) NOT NULL,leida TINYINT(1) NOT NULL DEFAULT 0,leida_en DATETIME,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_notif_usuario(usuario_id,deleted_at,leida),KEY idx_notif_origen(origen_tabla,origen_id,usuario_id,dias_restantes,created_at),CONSTRAINT fk_notif_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Actividad (Secuencia 5 - actividad.sql): bitacora legible de acciones de
-- usuarios (crear/editar/eliminar/restaurar/login/logout). Distinta de
-- auditoria_cambios (diffs JSON tecnicos, no sincronizada aqui porque ese
-- bloque IAM/RBAC de este schema.sql sigue desactualizado respecto a la BD
-- real de la Secuencia 1 -- ver nota en el diccionario de datos secuencia 5;
-- por eso tampoco se replican aqui los INSERT de permisos/permisos_rol,
-- ya que esas tablas no existen en este snapshot.
CREATE TABLE actividad_log(id INT UNSIGNED NOT NULL AUTO_INCREMENT,usuario_id INT UNSIGNED,modulo VARCHAR(50) NOT NULL,accion VARCHAR(30) NOT NULL,descripcion VARCHAR(255) NOT NULL,referencia_tabla VARCHAR(64),referencia_id INT UNSIGNED,ip_address VARCHAR(45),creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_actividad_usuario_fecha(usuario_id,created_at),KEY idx_actividad_modulo(modulo),KEY idx_actividad_fecha(created_at),CONSTRAINT fk_actividad_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Facturas HL (Secuencia 6 - facturas hl.sql): modulo espejo de facturas
-- (ARDUM/Secuencia 2) pero para Hegewisch Lopez, la consultora -- no para
-- propietarios de condominio. Por eso no referencia propietarios: usa un
-- campo de texto libre `cliente`. Requiere una fila en empresas (id=3,
-- 'Hegewisch Lopez', fuera de este snapshot igual que el resto de la
-- tabla empresas) solo como bucket de documentos.empresa_id al subir
-- comprobantes; no se expone como "empresa" navegable en el frontend.
CREATE TABLE facturas_hl(id INT UNSIGNED NOT NULL AUTO_INCREMENT,cliente VARCHAR(180) NOT NULL,fecha DATE NOT NULL,comprobante_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_facturas_hl_fecha(fecha),KEY idx_facturas_hl_deleted(deleted_at),CONSTRAINT fk_facturas_hl_comprobante FOREIGN KEY(comprobante_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
