SET FOREIGN_KEY_CHECKS=0; SET NAMES utf8mb4;
-- IAM/RBAC (Secuencia 1 - creacion usuarios.sql, con el fix de nombre de rol
-- 'viewer'->'Visor' y las columnas reset_token_* de la Secuencia 9). Este
-- bloque estuvo desactualizado (una version legacy sin personas/estados que
-- provoco un 500 en /api/auth/login en un despliegue nuevo) hasta que se
-- sincronizo aqui.
CREATE TABLE cat_paises(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,codigo_iso CHAR(2) NOT NULL UNIQUE,nombre VARCHAR(100) NOT NULL UNIQUE,activo TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE cat_tipos_documento(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clave VARCHAR(20) NOT NULL UNIQUE,nombre VARCHAR(100) NOT NULL,descripcion VARCHAR(255),activo TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE cat_estados_usuario(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clave VARCHAR(30) NOT NULL UNIQUE,nombre VARCHAR(60) NOT NULL,descripcion VARCHAR(255),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE personas(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tipo_documento_id INT UNSIGNED NOT NULL,pais_id INT UNSIGNED NOT NULL,nombre VARCHAR(100) NOT NULL,apellido_paterno VARCHAR(100) NOT NULL,apellido_materno VARCHAR(100) NOT NULL,fecha_nacimiento DATE NOT NULL,curp CHAR(18) NOT NULL UNIQUE,rfc VARCHAR(13),email VARCHAR(255) NOT NULL UNIQUE,telefono VARCHAR(20),creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,FOREIGN KEY(tipo_documento_id) REFERENCES cat_tipos_documento(id),FOREIGN KEY(pais_id) REFERENCES cat_paises(id),INDEX idx_nombre(apellido_paterno,apellido_materno,nombre),INDEX idx_email(email),INDEX idx_deleted(deleted_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE roles(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(50) NOT NULL UNIQUE,descripcion VARCHAR(255),activo TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE permisos(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL UNIQUE,modulo VARCHAR(50) NOT NULL,accion VARCHAR(50) NOT NULL,descripcion VARCHAR(255),creado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_modulo_accion(modulo,accion))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE permisos_rol(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,rol_id INT UNSIGNED NOT NULL,permiso_id INT UNSIGNED NOT NULL,creado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_rol_permiso(rol_id,permiso_id),FOREIGN KEY(rol_id) REFERENCES roles(id) ON DELETE CASCADE,FOREIGN KEY(permiso_id) REFERENCES permisos(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE usuarios(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,persona_id INT UNSIGNED NOT NULL UNIQUE,rol_id INT UNSIGNED NOT NULL,estado_id INT UNSIGNED NOT NULL,username VARCHAR(50) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,salt VARCHAR(64),intentos_fallidos TINYINT NOT NULL DEFAULT 0,bloqueado_hasta DATETIME,reset_token_hash VARCHAR(128),reset_token_expires_at DATETIME,ultimo_login DATETIME,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,FOREIGN KEY(persona_id) REFERENCES personas(id) ON DELETE RESTRICT,FOREIGN KEY(rol_id) REFERENCES roles(id) ON DELETE RESTRICT,FOREIGN KEY(estado_id) REFERENCES cat_estados_usuario(id) ON DELETE RESTRICT,INDEX idx_username(username),INDEX idx_deleted(deleted_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE usuarios_hist(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario_id INT UNSIGNED NOT NULL,rol_id INT UNSIGNED NOT NULL,estado_id INT UNSIGNED NOT NULL,password_hash VARCHAR(255) NOT NULL,salt VARCHAR(64),intentos_fallidos TINYINT NOT NULL,bloqueado_hasta DATETIME,operacion ENUM('UPDATE','DELETE') NOT NULL,modificado_por INT UNSIGNED,fecha_operacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_usuario(usuario_id),FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE sesiones(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario_id INT UNSIGNED NOT NULL,token VARCHAR(255) NOT NULL UNIQUE,ip_address VARCHAR(45),user_agent VARCHAR(512),expira_en DATETIME NOT NULL,cerrada_en DATETIME,motivo_cierre ENUM('LOGOUT','EXPIRACION','ADMIN','OTRO'),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,INDEX idx_token(token),INDEX idx_expira_en(expira_en),INDEX idx_usuario(usuario_id,cerrada_en))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE intentos_login(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario_id INT UNSIGNED,exitoso TINYINT(1) NOT NULL DEFAULT 0,ip_address VARCHAR(45),user_agent VARCHAR(512),descripcion VARCHAR(255),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,INDEX idx_usuario_fecha(usuario_id,created_at),INDEX idx_ip_fecha(ip_address,created_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE auditoria_cambios(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tabla_nombre VARCHAR(64) NOT NULL,registro_id INT UNSIGNED NOT NULL,operacion ENUM('INSERT','UPDATE','DELETE') NOT NULL,datos_anteriores JSON,datos_nuevos JSON,usuario_id INT UNSIGNED,ip_address VARCHAR(45),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,INDEX idx_tabla_registro(tabla_nombre,registro_id),INDEX idx_usuario(usuario_id),INDEX idx_fecha(created_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE apariencia(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario_id INT UNSIGNED NOT NULL UNIQUE,modo_oscuro TINYINT(1) NOT NULL DEFAULT 0,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TRIGGER IF EXISTS trg_usuarios_before_update;
CREATE TRIGGER trg_usuarios_before_update BEFORE UPDATE ON usuarios FOR EACH ROW INSERT INTO usuarios_hist(usuario_id,rol_id,estado_id,password_hash,salt,intentos_fallidos,bloqueado_hasta,operacion,modificado_por) VALUES(OLD.id,OLD.rol_id,OLD.estado_id,OLD.password_hash,OLD.salt,OLD.intentos_fallidos,OLD.bloqueado_hasta,'UPDATE',NEW.modificado_por);
DROP TRIGGER IF EXISTS trg_usuarios_before_delete;
CREATE TRIGGER trg_usuarios_before_delete BEFORE DELETE ON usuarios FOR EACH ROW INSERT INTO usuarios_hist(usuario_id,rol_id,estado_id,password_hash,salt,intentos_fallidos,bloqueado_hasta,operacion,modificado_por) VALUES(OLD.id,OLD.rol_id,OLD.estado_id,OLD.password_hash,OLD.salt,OLD.intentos_fallidos,OLD.bloqueado_hasta,'DELETE',OLD.modificado_por);
INSERT IGNORE INTO cat_paises(codigo_iso,nombre) VALUES('MX','México'),('US','Estados Unidos'),('ES','España');
INSERT IGNORE INTO cat_tipos_documento(clave,nombre) VALUES('CURP','CURP'),('INE','Credencial INE'),('PASAPORTE','Pasaporte');
INSERT IGNORE INTO cat_estados_usuario(clave,nombre) VALUES('ACTIVO','Activo'),('BLOQUEADO','Bloqueado temporalmente'),('INACTIVO','Inactivo'),('ELIMINADO','Eliminado lógicamente');
INSERT IGNORE INTO roles(nombre,descripcion) VALUES('superadmin','Acceso total al sistema y configuraciones'),('admin','Administración de usuarios y expedientes generales'),('editor','Captura, foliado y modificación de documentos'),('Visor','Consulta y visualización de expedientes sin permisos de edición');
INSERT IGNORE INTO permisos(nombre,modulo,accion,descripcion) VALUES('auth.login','AUTH','LOGIN','Iniciar sesión en el aplicativo'),('usuarios.crear','USUARIOS','CREAR','Dar de alta nuevos usuarios y colaboradores'),('usuarios.leer','USUARIOS','LEER','Consultar padrón de usuarios'),('usuarios.editar','USUARIOS','EDITAR','Actualizar datos de usuarios y asignar roles'),('documentos.crear','DOCUMENTOS','CREAR','Cargar y radicar nuevos documentos'),('documentos.leer','DOCUMENTOS','LEER','Visualizar y descargar expedientes'),('documentos.editar','DOCUMENTOS','EDITAR','Modificar metadatos o versionar documentos');
INSERT IGNORE INTO permisos_rol(rol_id,permiso_id) SELECT r.id,p.id FROM roles r JOIN permisos p ON 1=1 WHERE r.nombre='superadmin';
INSERT IGNORE INTO permisos_rol(rol_id,permiso_id) SELECT r.id,p.id FROM roles r JOIN permisos p ON 1=1 WHERE r.nombre='admin' AND p.nombre IN('auth.login','usuarios.crear','usuarios.leer','usuarios.editar','documentos.crear','documentos.leer','documentos.editar');
INSERT IGNORE INTO permisos_rol(rol_id,permiso_id) SELECT r.id,p.id FROM roles r JOIN permisos p ON 1=1 WHERE r.nombre='editor' AND p.nombre IN('auth.login','usuarios.leer','documentos.crear','documentos.leer','documentos.editar');
INSERT IGNORE INTO permisos_rol(rol_id,permiso_id) SELECT r.id,p.id FROM roles r JOIN permisos p ON 1=1 WHERE r.nombre='Visor' AND p.nombre IN('auth.login','documentos.leer');
INSERT IGNORE INTO personas(id,tipo_documento_id,pais_id,nombre,apellido_paterno,apellido_materno,fecha_nacimiento,curp,rfc,email,telefono) VALUES(1,(SELECT id FROM cat_tipos_documento WHERE clave='CURP'),(SELECT id FROM cat_paises WHERE codigo_iso='MX'),'Administrador','Sistema','General','1990-01-01','ASG900101HDFRXX01','ASG900101000','admin@gdprod.local','5555555555');
INSERT IGNORE INTO usuarios(id,persona_id,rol_id,estado_id,username,password_hash) VALUES(1,1,(SELECT id FROM roles WHERE nombre='superadmin'),(SELECT id FROM cat_estados_usuario WHERE clave='ACTIVO'),'admin','$2a$10$NSDpqY3LqyuBZZxZt/fEtOeuCzHANYXnfVlyoU00JmNwOpv7x4gmu');
-- Subroles (Secuencia 7 - subroles.sql): control de acceso por modulo de
-- negocio (ARDUM/ARDUM HL/Empresas Chinas) solo para roles editor/Visor;
-- admin/superadmin no usan subrol (acceso total siempre).
CREATE TABLE subroles(id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,clave VARCHAR(30) NOT NULL,nombre VARCHAR(60) NOT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_subrol_clave(clave))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE usuario_subroles(id INT UNSIGNED NOT NULL AUTO_INCREMENT,usuario_id INT UNSIGNED NOT NULL,subrol_id SMALLINT UNSIGNED NOT NULL,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_usuario_subrol(usuario_id,subrol_id),KEY idx_us_subrol(subrol_id),CONSTRAINT fk_us_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,CONSTRAINT fk_us_subrol FOREIGN KEY(subrol_id) REFERENCES subroles(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO subroles(clave,nombre) VALUES('ARDUM','ARDUM'),('ARDUM_HL','ARDUM HL'),('EMPRESAS_CHINAS','Empresas Chinas');
-- ARDUM (Secuencia 2 - ardum.sql): empresas..valores_columnas_personalizadas
-- sincronizadas con la BD real. Todas incluyen columnas de auditoria
-- (creado_por, modificado_por, created_at, updated_at) por convencion.
CREATE TABLE empresas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,nombre VARCHAR(150) NOT NULL,tipo ENUM('nacional','china') NOT NULL DEFAULT 'nacional',slug VARCHAR(160) NOT NULL,activa TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_empresas_slug(slug),KEY idx_empresas_tipo(tipo))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE empresa_usuario(empresa_id INT UNSIGNED NOT NULL,usuario_id INT UNSIGNED NOT NULL,PRIMARY KEY(empresa_id,usuario_id),KEY idx_eu_usuario(usuario_id),CONSTRAINT fk_eu_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id) ON DELETE CASCADE,CONSTRAINT fk_eu_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE propietarios(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,nombre VARCHAR(180) NOT NULL,numero_lote VARCHAR(20),curp CHAR(18),email VARCHAR(180),telefono VARCHAR(20),activo TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_propietarios_empresa(empresa_id),KEY idx_propietarios_curp(curp),KEY idx_propietarios_numero_lote(numero_lote),KEY idx_propietarios_deleted(deleted_at),CONSTRAINT fk_prop_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE tipos_documento(id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,clave VARCHAR(60) NOT NULL,nombre VARCHAR(180) NOT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_tipos_doc_clave(clave))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO empresas(id,nombre,tipo,slug) VALUES(1,'ARDUM','nacional','ardum'),(2,'Empresas Chinas','china','empresas-chinas'),(3,'Hegewisch Lopez','nacional','hegewisch-lopez');
INSERT IGNORE INTO tipos_documento(clave,nombre) VALUES('CONTRATO_ARDUM','Contrato Ardum'),('CONTRATO_HEGEWISCH','Contrato Hegewisch'),('CSF','Constancia de Situación Fiscal'),('ACUSE_CITA','Acuse de cita'),('FIEL_CLAVE','Clave privada (.key)'),('FIEL_CERTIFICADO','Certificado (.cer)'),('FIEL_CONTRASENA','Contraseña de la FIEL (.txt)'),('COMPROBANTE','Comprobante de pago');
CREATE TABLE documentos(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,propietario_id INT UNSIGNED,tipo_documento_id SMALLINT UNSIGNED NOT NULL,nombre_archivo VARCHAR(300) NOT NULL,ruta_storage VARCHAR(500) NOT NULL,mime_type VARCHAR(100) NOT NULL,tamano_bytes INT UNSIGNED NOT NULL,subido_por INT UNSIGNED NOT NULL,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_docs_empresa(empresa_id),KEY idx_docs_propietario(propietario_id),KEY idx_docs_tipo(tipo_documento_id),KEY idx_docs_deleted(deleted_at),CONSTRAINT fk_docs_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id),CONSTRAINT fk_docs_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE SET NULL,CONSTRAINT fk_docs_tipo FOREIGN KEY(tipo_documento_id) REFERENCES tipos_documento(id),CONSTRAINT fk_docs_subido FOREIGN KEY(subido_por) REFERENCES usuarios(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE columnas_personalizadas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,seccion VARCHAR(80) NOT NULL,nombre VARCHAR(120) NOT NULL,tipo ENUM('texto','numero','fecha','archivo','boolean') NOT NULL DEFAULT 'texto',orden SMALLINT UNSIGNED NOT NULL DEFAULT 0,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_col_empresa_seccion(empresa_id,seccion),KEY idx_colpers_deleted(deleted_at),CONSTRAINT fk_col_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- NOTA: Empresas Chinas (Secuencia 4) no tiene UI de columnas personalizadas,
-- por lo que valores_columnas_personalizadas no requiere empresa_china_id.
CREATE TABLE valores_columnas_personalizadas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,columna_id INT UNSIGNED NOT NULL,propietario_id INT UNSIGNED NOT NULL,valor_texto TEXT,valor_documento_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_vcp_columna_propietario(columna_id,propietario_id),KEY idx_vcp_columna(columna_id),KEY idx_vcp_propietario(propietario_id),CONSTRAINT fk_vcp_columna FOREIGN KEY(columna_id) REFERENCES columnas_personalizadas(id) ON DELETE CASCADE,CONSTRAINT fk_vcp_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_vcp_documento FOREIGN KEY(valor_documento_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE documentos_personales(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,contrato_ardum_id INT UNSIGNED,contrato_hegewisch_id INT UNSIGNED,csf_id INT UNSIGNED,acuse_cita_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_dp_propietario(propietario_id),KEY idx_docpers_deleted(deleted_at),CONSTRAINT fk_dp_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_dp_ardum FOREIGN KEY(contrato_ardum_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_dp_hegewisch FOREIGN KEY(contrato_hegewisch_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_dp_csf FOREIGN KEY(csf_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_dp_acuse FOREIGN KEY(acuse_cita_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE fiel_registros(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,clave_privada_id INT UNSIGNED,certificado_id INT UNSIGNED,contrasena VARCHAR(500),fecha_creacion DATE,fecha_vencimiento DATE,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_fiel_propietario(propietario_id),KEY idx_fiel_deleted(deleted_at),KEY idx_fiel_vencimiento(fecha_vencimiento),CONSTRAINT fk_fiel_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_fiel_clave FOREIGN KEY(clave_privada_id) REFERENCES documentos(id) ON DELETE SET NULL,CONSTRAINT fk_fiel_cert FOREIGN KEY(certificado_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Avisos de FIEL por correo (Secuencia 9): evita reenviar el mismo aviso por
-- email para el mismo fiel_id y el mismo umbral de dias_restantes.
CREATE TABLE fiel_avisos_email_log(id INT UNSIGNED NOT NULL AUTO_INCREMENT,fiel_id INT UNSIGNED NOT NULL,dias_restantes SMALLINT NOT NULL,email_destino VARCHAR(255) NOT NULL,enviado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_fiel_avisos_fiel_dias(fiel_id,dias_restantes),CONSTRAINT fk_fiel_avisos_fiel FOREIGN KEY(fiel_id) REFERENCES fiel_registros(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE declaraciones(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,tipo ENUM('mensual','mensual_cero') NOT NULL DEFAULT 'mensual',siguiente_pago_frecuencia ENUM('mensual','bimestral','anual') NOT NULL DEFAULT 'mensual',fecha_ultimo_pago DATE,fecha_declaracion DATE,comprobante_id INT UNSIGNED,periodo_mes TINYINT UNSIGNED NOT NULL,periodo_anio YEAR NOT NULL,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_decl_propietario(propietario_id),KEY idx_decl_periodo(periodo_anio,periodo_mes),KEY idx_decl_deleted(deleted_at),CONSTRAINT fk_decl_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_decl_comprobante FOREIGN KEY(comprobante_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE facturas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,propietario_id INT UNSIGNED NOT NULL,fecha DATE NOT NULL,comprobante_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_fact_propietario(propietario_id),KEY idx_fact_fecha(fecha),KEY idx_fact_deleted(deleted_at),CONSTRAINT fk_fact_propietario FOREIGN KEY(propietario_id) REFERENCES propietarios(id) ON DELETE CASCADE,CONSTRAINT fk_fact_comprobante FOREIGN KEY(comprobante_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Empresas Chinas (Secuencia 4 - empresas chinas.sql): auditoria completa +
-- deleted_at donde aplica papelera, mismas reglas que ARDUM (Secuencia 2).
CREATE TABLE etapa_requisitos(id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,etapa_num TINYINT UNSIGNED NOT NULL,codigo VARCHAR(10) NOT NULL,descripcion VARCHAR(500) NOT NULL,tipo_campo ENUM('archivo','texto','numero','boolean') NOT NULL DEFAULT 'archivo',creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_etapa_req_codigo(etapa_num,codigo),KEY idx_er_etapa(etapa_num))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO etapa_requisitos(etapa_num,codigo,descripcion,tipo_campo) VALUES(1,'1.1','Aprobación del nombre de la empresa','archivo'),(1,'1.2','Una cuenta de correo electrónico','texto'),(1,'1.3','Un número de teléfono celular mexicano','texto'),(1,'1.4','Copia de Identificación China','archivo'),(1,'1.5','Acta de Matrimonio apostillada','archivo'),(1,'1.6','Identificación de representantes legales','archivo'),(1,'1.7','Comprobante de domicilio de representantes legales','archivo'),(1,'1.8','Constancia de situación fiscal de los representantes legales','archivo'),(1,'1.9','CURP Mexicano','archivo'),(1,'1.10','Datos Generales PLD','archivo'),(1,'1.11','Formato de notaría con los datos de la sociedad a constituir','archivo'),(1,'1.12','Actividad Económica','archivo'),(1,'1.13','Carta Poder','archivo'),(1,'1.14','Traducción de Certificado notarial apostillado','archivo'),(1,'1.15','Comisionario Mexicano: INE CURP RFC comprobante','archivo'),(1,'1.16','Firma de representante legal en los estatus sociales','texto'),(1,'1.17','Acta Constitutiva Registro Comercio Publico','archivo'),(2,'2.1','Agenda cita para tramitar el RFC','archivo'),(2,'2.2','Acuse de cita impreso','archivo'),(2,'2.3','Comprobante de domicilio de la empresa','archivo'),(2,'2.4','Acta constitutiva','archivo'),(2,'2.5','Identificación del representante legal','archivo'),(2,'2.6','Una cuenta de correo electrónico','texto'),(2,'2.7','Un número de teléfono celular mexicano','texto'),(2,'2.8','Situación fiscal','archivo'),(3,'3.1','Agenda cita de firma electrónica','archivo'),(3,'3.2','Acuse de cita','archivo'),(3,'3.3','Constancia de situación fiscal de la empresa','archivo'),(3,'3.4','Comprobante de domicilio de la empresa','archivo'),(3,'3.5','Acta constitutiva','archivo'),(3,'3.6','Identificación del representante legal','archivo'),(3,'3.7','Memoria USB','texto'),(3,'3.8','Un correo electrónico','texto'),(3,'3.9','Un número de teléfono mexicano','texto'),(3,'3.10','Un representante legal en México lleva los documentos necesarios a la autoridad fiscal para solicitar RFC','texto'),(3,'3.11','Firma electrónica de la empresa','archivo'),(4,'4.1','Acta constitutiva','archivo'),(4,'4.2','Constancia de situación fiscal','archivo'),(4,'4.3','Pasaporte o tarjeta de residencia del representante legal','archivo'),(4,'4.4','Comprobante de domicilio del representante legal','archivo'),(4,'4.5','Comprobante de domicilio de la empresa','archivo'),(4,'4.6','Numero de celular para banca electrónica','texto'),(4,'4.7','Solicitud de cuenta bancaria','archivo'),(4,'4.8','Cuenta bancario y banca móvil','archivo'),(5,'5.1','Registro ante el IMSS','archivo'),(5,'5.2','Registro nacional de inversiones extranjeras RNIE','archivo'),(5,'5.3','Registro internos corporativos','archivo');
CREATE TABLE empresas_chinas(id INT UNSIGNED NOT NULL AUTO_INCREMENT,codigo VARCHAR(20) NOT NULL,nombre VARCHAR(180) NOT NULL,representante_legal VARCHAR(180),correo_electronico VARCHAR(180),telefono VARCHAR(30),fecha_registro DATE,etapa_actual TINYINT UNSIGNED NOT NULL DEFAULT 1,estado ENUM('en_proceso','pendiente','finalizada','archivada') NOT NULL DEFAULT 'en_proceso',progreso_pct TINYINT UNSIGNED NOT NULL DEFAULT 0,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_ec_codigo(codigo),KEY idx_ec_estado(estado),KEY idx_ec_deleted(deleted_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE empresa_china_requisitos(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_china_id INT UNSIGNED NOT NULL,requisito_id SMALLINT UNSIGNED NOT NULL,documento_id INT UNSIGNED,valor_texto TEXT,completado TINYINT(1) NOT NULL DEFAULT 0,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),UNIQUE KEY uq_ecr(empresa_china_id,requisito_id),KEY idx_ecr_deleted(deleted_at),CONSTRAINT fk_ecr_empresa FOREIGN KEY(empresa_china_id) REFERENCES empresas_chinas(id) ON DELETE CASCADE,CONSTRAINT fk_ecr_requisito FOREIGN KEY(requisito_id) REFERENCES etapa_requisitos(id),CONSTRAINT fk_ecr_documento FOREIGN KEY(documento_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE empresa_china_etapa_checklist(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_china_id INT UNSIGNED NOT NULL,etapa_num TINYINT UNSIGNED NOT NULL,completada TINYINT(1) NOT NULL DEFAULT 0,completada_en DATETIME,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_ecec(empresa_china_id,etapa_num),CONSTRAINT fk_ecec_empresa FOREIGN KEY(empresa_china_id) REFERENCES empresas_chinas(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE configuracion_notificaciones(id INT UNSIGNED NOT NULL AUTO_INCREMENT,empresa_id INT UNSIGNED NOT NULL,tipo VARCHAR(80) NOT NULL,dia_del_mes TINYINT UNSIGNED NOT NULL,activa TINYINT(1) NOT NULL DEFAULT 1,PRIMARY KEY(id),KEY idx_cn_empresa(empresa_id),CONSTRAINT fk_cn_empresa FOREIGN KEY(empresa_id) REFERENCES empresas(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Configuracion alertas FIEL (Secuencia 8 - configuracion alertas fiel.sql):
-- singleton (id=1) con los dias de anticipacion del job de vencimientos de
-- FIEL, configurable por admin/superadmin desde el modulo Configuracion.
CREATE TABLE configuracion_alertas_fiel(id TINYINT UNSIGNED NOT NULL,dias_anticipacion TINYINT UNSIGNED NOT NULL DEFAULT 3,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO configuracion_alertas_fiel(id,dias_anticipacion) VALUES(1,3);
-- Notificaciones (Secuencia 3 - notificaciones.sql): generica y reutilizable
-- via origen_tabla/origen_id; hoy alimentada por el job de vencimientos FIEL.
CREATE TABLE notificaciones(id INT UNSIGNED NOT NULL AUTO_INCREMENT,usuario_id INT UNSIGNED NOT NULL,tipo VARCHAR(60) NOT NULL,origen_tabla VARCHAR(60) NOT NULL,origen_id INT UNSIGNED NOT NULL,dias_restantes TINYINT NOT NULL,titulo VARCHAR(200) NOT NULL,cuerpo VARCHAR(500) NOT NULL,ruta VARCHAR(300) NOT NULL,leida TINYINT(1) NOT NULL DEFAULT 0,leida_en DATETIME,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_notif_usuario(usuario_id,deleted_at,leida),KEY idx_notif_origen(origen_tabla,origen_id,usuario_id,dias_restantes,created_at),CONSTRAINT fk_notif_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Actividad (Secuencia 5 - actividad.sql): bitacora legible de acciones de
-- usuarios (crear/editar/eliminar/restaurar/login/logout). Distinta de
-- auditoria_cambios (diffs JSON tecnicos de la Secuencia 1, ya creada arriba).
CREATE TABLE actividad_log(id INT UNSIGNED NOT NULL AUTO_INCREMENT,usuario_id INT UNSIGNED,modulo VARCHAR(50) NOT NULL,accion VARCHAR(30) NOT NULL,descripcion VARCHAR(255) NOT NULL,referencia_tabla VARCHAR(64),referencia_id INT UNSIGNED,ip_address VARCHAR(45),creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_actividad_usuario_fecha(usuario_id,created_at),KEY idx_actividad_modulo(modulo),KEY idx_actividad_fecha(created_at),CONSTRAINT fk_actividad_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO permisos(nombre,modulo,accion,descripcion) VALUES('actividad.leer','ACTIVIDAD','LEER','Consultar la bitacora de actividad del sistema');
INSERT IGNORE INTO permisos_rol(rol_id,permiso_id) SELECT r.id,p.id FROM roles r JOIN permisos p ON 1=1 WHERE r.nombre IN('superadmin','admin','editor','Visor') AND p.nombre='actividad.leer';
-- Facturas HL (Secuencia 6 - facturas hl.sql): modulo espejo de facturas
-- (ARDUM/Secuencia 2) pero para Hegewisch Lopez, la consultora -- no para
-- propietarios de condominio. Por eso no referencia propietarios: usa un
-- campo de texto libre `cliente`. Reutiliza la fila de empresas id=3
-- ('Hegewisch Lopez', sembrada arriba junto al resto de `empresas`) solo
-- como bucket de documentos.empresa_id al subir comprobantes; no se expone
-- como "empresa" navegable en el frontend.
CREATE TABLE facturas_hl(id INT UNSIGNED NOT NULL AUTO_INCREMENT,cliente VARCHAR(180) NOT NULL,fecha DATE NOT NULL,comprobante_id INT UNSIGNED,creado_por INT UNSIGNED,modificado_por INT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,PRIMARY KEY(id),KEY idx_facturas_hl_fecha(fecha),KEY idx_facturas_hl_deleted(deleted_at),CONSTRAINT fk_facturas_hl_comprobante FOREIGN KEY(comprobante_id) REFERENCES documentos(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
